project:
  type: website
  output-dir: docs

website:
  title: "mattdiekmann.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - eurobasket.qmd

format:
  html:
    theme:
      - jolla
      - brand
    css: styles.css
    toc: true



